---
- hosts: Test
  tasks:
  - name: create a normal container
    community.general.proxmox:
      api_user: "{{ proxmox_api_user }}"
      api_host: "{{ proxmox_api_host }}"
      api_token_id: "{{ proxmox_api_token_id }}"
      api_token_secret: "{{ proxmox_api_token_secret }}"
      state: started
      cpus: "{{ proxmox_cpus }}"
      cores: "{{ proxmox_cores }}"
      memory: "{{ proxmox_memory }}"
      swap: "{{ proxmox_swap }}"
      storage: "{{ proxmox_storage }}"
      hostname: "{{ proxmox_hostname }} "
      ostemplate: "{{ proxmox_base_image }}"
      mounts: '{"mp0":"/mnt/lxc_shares/nas_rwx/,mp=/mnt/nas"}'
      netif: '{"net0":"name=eth0,ip=dhcp,bridge=vmbr0,firewall=0,tag=10"}'
      features: "{{ proxmox_features }}"
      
  vars_prompt: 
    - name: password
      prompt: enter lxc password
