---
- hosts: Test
      
  tasks: 
  - name: Remove container
    community.general.proxmox:
      vmid: "{{ proxmox_vmid }}"
      api_user: "{{ proxmox_api_user }}"
      api_host: "{{ proxmox_api_host }}"
      api_token_id: "{{ proxmox_api_token_id }}"
      api_token_secret: "{{ proxmox_api_token_secret }}"
      state: absent
